DROP SCHEMA IF EXISTS gdelt CASCADE;
CREATE SCHEMA gdelt;
GRANT ALL ON SCHEMA gdelt TO PUBLIC;

-- Create tables and load lookups

CREATE TABLE gdelt.events (
  globaleventid INT,
  day INT,
  monthyear INT,
  year INT,
  fractiondate FLOAT,
  actor1code VARCHAR(max),
  actor1name VARCHAR(max),
  actor1countrycode VARCHAR(max),
  actor1knowngroupcode VARCHAR(max),
  actor1ethniccode VARCHAR(max),
  actor1religion1code VARCHAR(max),
  actor1religion2code VARCHAR(max),
  actor1type1code VARCHAR(max),
  actor1type2code VARCHAR(max),
  actor1type3code VARCHAR(max),
  actor2code VARCHAR(max),
  actor2name VARCHAR(max),
  actor2countrycode VARCHAR(max),
  actor2knowngroupcode VARCHAR(max),
  actor2ethniccode VARCHAR(max),
  actor2religion1code VARCHAR(max),
  actor2religion2code VARCHAR(max),
  actor2type1code VARCHAR(max),
  actor2type2code VARCHAR(max),
  actor2type3code VARCHAR(max),
  isrootevent BOOLEAN,
  eventcode VARCHAR(max),
  eventbasecode VARCHAR(max),
  eventrootcode VARCHAR(max),
  quadclass INT,
  goldsteinscale FLOAT,
  nummentions INT,
  numsources INT,
  numarticles INT,
  avgtone FLOAT,
  actor1geo_type INT,
  actor1geo_fullname VARCHAR(max),
  actor1geo_countrycode VARCHAR(max),
  actor1geo_adm1code VARCHAR(max),
  actor1geo_adm2code VARCHAR(max),
  actor1geo_lat FLOAT,
  actor1geo_long FLOAT,
  actor1geo_featureid VARCHAR(max),
  actor2geo_type INT,
  actor2geo_fullname VARCHAR(max),
  actor2geo_countrycode VARCHAR(max),
  actor2geo_adm1code VARCHAR(max),
  actor2geo_adm2code VARCHAR(max),
  actor2geo_lat FLOAT,
  actor2geo_long FLOAT,
  actor2geo_featureid VARCHAR(max),
  actiongeo_type INT,
  actiongeo_fullname VARCHAR(max),
  actiongeo_countrycode VARCHAR(max),
  actiongeo_adm1code VARCHAR(max),
  actiongeo_adm2code VARCHAR(max),
  actiongeo_lat FLOAT,
  actiongeo_long FLOAT,
  actiongeo_featureid VARCHAR(max),
  dateadded BIGINT,
  sourceurl VARCHAR(max))
DISTRIBUTE RANDOM;
GRANT ALL ON TABLE gdelt.events TO public;

CREATE TABLE gdelt.gkg (
  gkgrecordid varchar(max),
  date bigint,
  sourcecollectionidentifier int,
  sourcecommonname varchar(max),
  documentidentifier varchar(max),
  counts varchar(max),
  v2counts varchar(max),
  themes varchar(max),
  v2themes varchar(max),
  locations varchar(max),
  v2locations varchar(max),
  persons varchar(max),
  v2persons varchar(max),
  organizations varchar(max),
  v2organizations varchar(max),
  v2tone varchar(max),
  dates varchar(max),
  gcam varchar(max),
  sharingimage varchar(max),
  relatedimages varchar(max),
  socialimageembeds varchar(max),
  socialvideoembeds varchar(max),
  quotations varchar(max),
  allnames varchar(max),
  amounts varchar(max),
  translationinfo varchar(max),
  extras varchar(max))
DISTRIBUTE ON (gkgrecordid);
GRANT ALL ON TABLE gdelt.gkg TO public;

CREATE TABLE gdelt.mentions (
  globaleventid INT,
  eventtimedate BIGINT,
  mentiontimedate BIGINT,
  mentiontype INT,
  mentionsourcename VARCHAR(max),
  mentionidentifier VARCHAR(max),
  sentenceid INT,
  actor1charoffset INT,
  actor2charoffset INT,
  actioncharoffset INT,
  inrawtext INT,
  confidence INT,
  mentiondoclen INT,
  mentiondoctone FLOAT,
  mentiondoctranslationinfo VARCHAR(max),
  extras VARCHAR(max)
)
DISTRIBUTE RANDOM;
GRANT ALL ON TABLE gdelt.mentions TO public;

CREATE TABLE gdelt.eventcodes (code VARCHAR(max), description VARCHAR(max)) DISTRIBUTE REPLICATE;
GRANT ALL ON TABLE gdelt.eventcodes TO public;
INSERT INTO gdelt.eventcodes VALUES
('01', 'MAKE PUBLIC STATEMENT'),
('010', 'Make statement, not specified below'),
('011', 'Decline comment'),
('012', 'Make pessimistic comment'),
('013', 'Make optimistic comment'),
('014', 'Consider policy option'),
('015', 'Acknowledge or claim responsibility'),
('016', 'Deny responsibility'),
('017', 'Engage in symbolic act'),
('018', 'Make empathetic comment'),
('019', 'Express accord'),
('02', 'APPEAL'),
('020', 'Appeal, not specified below'),
('021', 'Appeal for material cooperation, not specified below'),
('0211', 'Appeal for economic cooperation'),
('0212', 'Appeal for military cooperation'),
('0213', 'Appeal for judicial cooperation'),
('0214', 'Appeal for intelligence'),
('022', 'Appeal for diplomatic cooperation, such as policy support'),
('023', 'Appeal for aid, not specified below'),
('0231', 'Appeal for economic aid'),
('0232', 'Appeal for military aid'),
('0233', 'Appeal for humanitarian aid'),
('0234', 'Appeal for military protection or peacekeeping'),
('024', 'Appeal for political reform, not specified below'),
('0241', 'Appeal for change in leadership'),
('0242', 'Appeal for policy change'),
('0243', 'Appeal for rights'),
('0244', 'Appeal for change in institutions, regime'),
('025', 'Appeal to yield'),
('0251', 'Appeal for easing of administrative sanctions'),
('0252', 'Appeal for easing of popular dissent'),
('0253', 'Appeal for release of persons or property'),
('0254', 'Appeal for easing of economic sanctions, boycott, or embargo'),
('0255', 'Appeal for target to allow international involvement (non-mediation)'),
('0256', 'Appeal for de-escalation of military engagement'),
('026', 'Appeal to others to meet or negotiate'),
('027', 'Appeal to others to settle dispute'),
('028', 'Appeal to others to engage in or accept mediation'),
('03', 'EXPRESS INTENT TO COOPERATE'),
('030', 'Express intent to cooperate, not specified below'),
('031', 'Express intent to engage in material cooperation,  not specified below'),
('0311', 'Express intent to cooperate economically'),
('0312', 'Express intent to cooperate militarily'),
('0313', 'Express intent to cooperate on judicial matters'),
('0314', 'Express intent to cooperate on intelligence'),
('032', 'Express intent to provide diplomatic cooperation such as policy support'),
('033', 'Express intent to provide matyerial aid, not specified below'),
('0331', 'Express intent to provide economic aid'),
('0332', 'Express intent to provide military aid'),
('0333', 'Express intent to provide humanitarian aid'),
('0334', 'Express intent to provide military protection or peacekeeping'),
('034', 'Express intent to institute political reform, not specified below'),
('0341', 'Express intent to change leadership'),
('0342', 'Express intent to change policy'),
('0343', 'Express intent to provide rights'),
('0344', 'Express intent to change institutions, regime'),
('035', 'Express intent to yield, not specified below'),
('0351', 'Express intent to ease administrative sanctions'),
('0352', 'Express intent to ease popular dissent'),
('0353', 'Express intent to release persons or property'),
('0354', 'Express intent to ease economic sanctions, boycott, or embargo'),
('0355', 'Express intent allow international involvement (not mediation)'),
('0356', 'Express intent to de-escalate military engagement '),
('036', 'Express intent to meet or negotiate'),
('037', 'Express intent to settle dispute'),
('038', 'Express intent to accept mediation'),
('039', 'Express intent to mediate'),
('04', 'CONSULT'),
('040', 'Consult, not specified below'),
('041', 'Discuss by telephone'),
('042', 'Make a visit'),
('043', 'Host a visit'),
('044', 'Meet at a ÒhirdÓlocation'),
('045', 'Mediate'),
('046', 'Engage in negotiation'),
('05', 'ENGAGE IN DIPLOMATIC COOPERATION'),
('050', 'Engage in diplomatic cooperation, not specified below'),
('051', 'Praise or endorse'),
('052', 'Defend verbally'),
('053', 'Rally support on behalf of'),
('054', 'Grant diplomatic recognition'),
('055', 'Apologize'),
('056', 'Forgive'),
('057', 'Sign formal agreement'),
('06', 'ENGAGE IN MATERIAL COOPERATION'),
('060', 'Engage in material cooperation, not specified below'),
('061', 'Cooperate economically'),
('062', 'Cooperate militarily'),
('063', 'Engage in judicial cooperation'),
('064', 'Share intelligence or information'),
('07', 'PROVIDE AID'),
('070', 'Provide aid, not specified below'),
('071', 'Provide economic aid'),
('072', 'Provide military aid'),
('073', 'Provide humanitarian aid'),
('074', 'Provide military protection or peacekeeping'),
('075', 'Grant asylum'),
('08', 'YIELD'),
('080', 'Yield, not specified below '),
('081', 'Ease administrative sanctions, not specified below'),
('0811', 'Ease restrictions on political freedoms'),
('0812', 'Ease ban on political parties or politicians'),
('0813', 'Ease curfew'),
('0814', 'Ease state of emergency or martial law'),
('082', 'Ease political dissent '),
('083', 'Accede to requests or demands for political reform not specified below'),
('0831', 'Accede to demands for change in leadership'),
('0832', 'Accede to demands for change in policy'),
('0833', 'Accede to demands for rights'),
('0834', 'Accede to demands for change in institutions, regime'),
('084', 'Return, release, not specified below'),
('0841', 'Return, release person(s)'),
('0842', 'Return, release property'),
('085', 'Ease economic sanctions, boycott, embargo'),
('086', 'Allow international involvement not specified below'),
('0861', 'Receive deployment of peacekeepers'),
('0862', 'Receive inspectors'),
('0863', 'Allow delivery of humanitarian aid'),
('087', 'De-escalate military engagement'),
('0871', 'Declare truce, ceasefire'),
('0872', 'Ease military blockade'),
('0873', 'Demobilize armed forces'),
('0874', 'Retreat or surrender militarily'),
('09', 'INVESTIGATE'),
('090', 'Investigate, not specified below'),
('091', 'Investigate crime, corruption'),
('092', 'Investigate human rights abuses'),
('093', 'Investigate military action'),
('094', 'Investigate war crimes'),
('10', 'DEMAND'),
('100', 'Demand, not specified below'),
('101', 'Demand information, investigation'),
('1011', 'Demand economic cooperation'),
('1012', 'Demand military cooperation'),
('1013', 'Demand judicial cooperation'),
('1014', 'Demand intelligence cooperation'),
('102', 'Demand policy support'),
('103', 'Demand aid, protection, or peacekeeping'),
('1031', 'Demand economic aid'),
('1032', 'Demand military aid'),
('1033', 'Demand humanitarian aid'),
('1034', 'Demand military protection or peacekeeping'),
('104', 'Demand political reform, not specified below'),
('1041', 'Demand change in leadership'),
('1042', 'Demand policy change'),
('1043', 'Demand rights'),
('1044', 'Demand change in institutions, regime'),
('105', 'Demand mediation'),
('1051', 'Demand easing of administrative sanctions'),
('1052', 'Demand easing of political dissent'),
('1053', 'Demand release of persons or property'),
('1054', 'Demand easing of economic sanctions, boycott, or embargo'),
('1055', 'Demand that target allows international involvement (non-mediation)'),
('1056', 'Demand de-escalation of military engagement106:[-5.0] Demand withdrawal'),
('107', 'Demand ceasefire'),
('108', 'Demand meeting, negotiation'),
('11', 'DISAPPROVE'),
('110', 'Disapprove, not specified below'),
('111', 'Criticize or denounce '),
('112', 'Accuse, not specified below'),
('1121', 'Accuse of crime, corruption'),
('1122', 'Accuse of human rights abuses'),
('1123', 'Accuse of aggression'),
('1124', 'Accuse of war crimes'),
('1125', 'Accuse of espionage, treason'),
('113', 'Rally opposition against'),
('114', 'Complain officially '),
('115', 'Bring lawsuit against '),
('116', 'Find guilty or liable (legally)'),
('12', 'REJECT'),
('120', 'Reject, not specified below'),
('121', 'Reject material cooperation'),
('1211', 'Reject economic cooperation'),
('1212', 'Reject military cooperation'),
('122', 'Reject request or demand for material aid, not specified below'),
('1221', 'Reject request for economic aid'),
('1222', 'Reject request for military aid'),
('1223', 'Reject request for humanitarian aid'),
('1224', 'Reject request for military protection or peacekeeping'),
('123', 'Reject request or demand for political reform, not specified below'),
('1231', 'Reject request for change in leadership'),
('1232', 'Reject request for policy change'),
('1233', 'Reject request for rights'),
('1234', 'Reject request for change in institutions, regime'),
('124', 'Refuse to yield, not specified below'),
('1241', 'Refuse to ease administrative sanctions'),
('1242', 'Refuse to ease popular dissent'),
('1243', 'Refuse to release persons or property'),
('1244', 'Refuse to ease economic sanctions, boycott, or embargo'),
('1245', 'Refuse to allow international involvement (non mediation)'),
('1246', 'Refuse to de-escalate military engagement'),
('125', 'Reject proposal to meet, discuss, or negotiate'),
('126', 'Reject mediation'),
('127', 'Reject plan, agreement to settle dispute'),
('128', 'Defy norms, law'),
('129', 'Veto'),
('13', 'THREATEN'),
('130', 'Threaten, not specified below'),
('131', 'Threaten non-force, not specified below'),
('1311', 'Threaten to reduce or stop aid'),
('1312', 'Threaten to boycott, embargo, or sanction'),
('1313', 'Threaten to reduce or break relations'),
('132', 'Threaten with administrative sanctions, not specified below'),
('1321', 'Threaten to impose restrictions on political freedoms '),
('1322', 'Threaten to ban political parties or politicians'),
('1323', 'Threaten to impose curfew'),
('1324', 'Threaten to impose state of emergency or martial law'),
('133', 'Threaten political dissent, protest'),
('134', 'Threaten to halt negotiations'),
('135', 'Threaten to halt mediation'),
('136', 'Threaten to halt international involvement (non-mediation)'),
('137', 'Threaten with violent repression'),
('138', 'Threaten to use military force, not specified below'),
('1381', 'Threaten blockade'),
('1382', 'Threaten occupation '),
('1383', 'Threaten unconventional violence '),
('1384', 'Threaten conventional attack  '),
('1385', 'Threaten attack with WMD'),
('139', 'Give ultimatum'),
('14', 'PROTEST'),
('140', 'Engage in political dissent, not specified below'),
('141', 'Demonstrate or rally'),
('1411', 'Demonstrate for leadership change'),
('1412', 'Demonstrate for policy change'),
('1413', 'Demonstrate for rights'),
('1414', 'Demonstrate for change in institutions, regime'),
('142', 'Conduct hunger strike, not specified below'),
('1421', 'Conduct hunger strike for leadership change'),
('1422', 'Conduct hunger strike for policy change'),
('1423', 'Conduct hunger strike for rights'),
('1424', 'Conduct hunger strike for change in institutions, regime '),
('143', 'Conduct strike or boycott, not specified below'),
('1431', 'Conduct strike or boycott for leadership change  '),
('1432', 'Conduct strike or boycott for policy change'),
('1433', 'Conduct strike or boycott for rights'),
('1434', 'Conduct strike or boycott for change in institutions, regime'),
('144', 'Obstruct passage, block'),
('1441', 'Obstruct passage to demand leadership change '),
('1442', 'Obstruct passage to demand policy change'),
('1443', 'Obstruct passage to demand rights'),
('1444', 'Obstruct passage to demand change in institutions, regime'),
('145', 'Protest violently, riot'),
('1451', 'Engage in violent protest for leadership change  '),
('1452', 'Engage in violent protest for policy change'),
('1453', 'Engage in violent protest for rights'),
('1454', 'Engage in violent protest for  change in institutions, regime'),
('15', 'EXHIBIT FORCE POSTURE'),
('150', 'Demonstrate military or police power, not specified below'),
('151', 'Increase police alert status'),
('152', 'Increase military alert status'),
('153', 'Mobilize or increase police power'),
('154', 'Mobilize or increase armed forces '),
('16', 'REDUCE RELATIONS'),
('160', 'Reduce relations, not specified below'),
('161', 'Reduce or break diplomatic relations'),
('162', 'Reduce or stop aid, not specified below'),
('1621', 'Reduce or stop economic assistance'),
('1622', 'Reduce or stop military assistance'),
('1623', 'Reduce or stop humanitarian assistance'),
('163', 'Impose embargo, boycott, or sanctions'),
('164', 'Halt negotiations'),
('165', 'Halt mediation'),
('166', 'Expel or withdraw, not specified below'),
('1661', 'Expel or withdraw peacekeepers'),
('1662', 'Expel or withdraw inspectors, observers'),
('1663', 'Expel or withdraw aid agencies'),
('17', 'COERCE'),
('170', 'Coerce, not specified below '),
('171', 'Seize or damage property, not specified below'),
('1711', 'Confiscate property'),
('1712', 'Destroy property'),
('172', 'Impose administrative sanctions, not specified below'),
('1721', 'Impose restrictions on political freedoms  '),
('1722', 'Ban political parties or politicians'),
('1723', 'Impose curfew'),
('1724', 'Impose state of emergency or martial law'),
('173', 'Arrest, detain, or charge with legal action '),
('174', 'Expel or deport individuals'),
('175', 'Use tactics of violent repression  '),
('18', 'ASSAULT'),
('180', 'Use unconventional violence, not specified below'),
('181', 'Abduct, hijack, or take hostage '),
('182', 'Physically assault, not specified below'),
('1821', 'Sexually assault'),
('1822', 'Torture'),
('1823', 'Kill by physical assault'),
('183', 'Conduct suicide, car, or other non-military bombing, not spec below'),
('1831', 'Carry out suicide bombing'),
('1832', 'Carry out car bombing'),
('1833', 'Carry out roadside bombing '),
('184', 'Use as human shield '),
('185', 'Attempt to assassinate'),
('186', 'Assassinate '),
('19', 'FIGHT'),
('190', 'Use conventional military force, not specified below'),
('191', 'Impose blockade, restrict movement '),
('192', 'Occupy territory'),
('193', 'Fight with small arms and light weapons'),
('194', 'Fight with artillery and tanks'),
('195', 'Employ aerial weapons'),
('196', 'Violate ceasefire '),
('20', 'USE UNCONVENTIONAL MASS VIOLENCE'),
('200', 'Use unconventional mass violence, not specified below'),
('201', 'Engage in mass expulsion'),
('202', 'Engage in mass killings'),
('203', 'Engage in ethnic cleansing'),
('204', 'Use weapons of mass destruction, not specified below'),
('2041', 'Use chemical, biological, or radiologicalweapons'),
('2042', 'Detonate nuclear weapons');
YFLUSH gdelt.eventcodes;

CREATE TABLE gdelt.types (type VARCHAR(max), description VARCHAR(max)) DISTRIBUTE REPLICATE;
GRANT ALL ON TABLE gdelt.types TO public;
INSERT INTO gdelt.types VALUES
('COP', 'Police forces'),
('GOV', 'Government'),
('INS', 'Insurgents'),
('JUD', 'Judiciary'),
('MIL', 'Military'),
('OPP', 'Political Opposition'),
('REB', 'Rebels'),
('SEP', 'Separatist Rebels'),
('SPY', 'State Intelligence'),
('UAF', 'Unaligned Armed Forces'),
('AGR', 'Agriculture'),
('BUS', 'Business'),
('CRM', 'Criminal'),
('CVL', 'Civilian'),
('DEV', 'Development'),
('EDU', 'Education'),
('ELI', 'Elites'),
('ENV', 'Environmental'),
('HLH', 'Health'),
('HRI', 'Human Rights'),
('LAB', 'Labor'),
('LEG', 'Legislature'),
('MED', 'Media'),
('REF', 'Refugees'),
('MOD', 'Moderate'),
('RAD', 'Radical'),
('AMN', 'Amnesty International'),
('IRC', 'Red Cross'),
('GRP', 'Greenpeace'),
('UNO', 'United Nations'),
('PKO', 'Peacekeepers'),
('UIS', 'Unidentified State Actor'),
('IGO', 'Inter-Governmental Organization'),
('IMG', 'International Militarized Group'),
('INT', 'International/Transnational Generic'),
('MNC', 'Multinational Corporation'),
('NGM', 'Non-Governmental Movement'),
('NGO', 'Non-Governmental Organization'),
('UIS', 'Unidentified State Actor'),
('SET', 'Settler');
YFLUSH gdelt.types;

CREATE TABLE gdelt.groups (_group VARCHAR(max), description VARCHAR(max)) DISTRIBUTE REPLICATE;
GRANT ALL ON TABLE gdelt.groups TO public;
INSERT INTO gdelt.groups VALUES
('AAM', 'Al Aqsa Martyrs Brigade'),
('ABD', 'Arab Bank for Economic Development in Africa'),
('ACC', 'Arab Cooperation Council'),
('ADB', 'Asian Development Bank'),
('AEU', 'Arab Economic Unity Council'),
('AFB', 'African Development Bank'),
('ALQ', 'Al Qaeda'),
('AMF', 'Arab Monetary Fund for Economic and Social Development'),
('AML', 'Amal Militia'),
('AMN', 'Amnesty International'),
('AMU', 'Arab Maghreb Union'),
('ANO', 'Abu Nidal Organization'),
('APE', 'Org. of Arab Petroleum Exporting Countries (OAPEC)'),
('ARL', 'Arab League'),
('ASL', 'South Lebanon Army'),
('ASN', 'Association of Southeast Asian Nations (ASEAN)'),
('ATD', 'Eastern and Southern African Trade and Development Bank'),
('BCA', 'Bank of Central African States (BEAC)'),
('BIS', 'Bank for International Settlements'),
('BTH', 'Baath Party'),
('CEM', 'Common Market for Eastern and Southern Africa'),
('CEM', 'Monetary and Economic Community of Central Africa'),
('CFA', 'Franc Zone Financial Community of Africa'),
('CIS', 'Commonwealth of Independent States'),
('CMN', 'Communist'),
('COE', 'Council of Europe'),
('CPA', 'Cocoa Producer''s Alliance'),
('CPC', 'Association of Coffee Producing Countries'),
('CRC', 'International Fed. of Red Cross and Red Crescent (ICRC)'),
('CSS', 'Community of Sahel-Saharan States (CENSAD)'),
('CWN', 'Commonwealth of Nations'),
('DFL', 'Democratic Front for the Lib. of Palestine (DFLP)'),
('EBR', 'European Bank for Reconstruction and Development'),
('ECA', 'Economic Community of Central African States'),
('EEC', 'European Union'),
('EFT', 'European Free Trade Association'),
('ENN', 'Ennahda Movement'),
('FAO', 'United Nations Food and Agriculture Organization'),
('FID', 'International Federation of Human Rights (FIDH)'),
('FIS', 'Islamic Salvation Army'),
('FLN', 'National Liberation Front (FLN)'),
('FTA', 'Fatah'),
('GCC', 'Gulf Cooperation Council'),
('GIA', 'Armed Islamic Group (GIA)'),
('GOE', 'Group of Eight (G-8) (G-7 plus Russia)'),
('GOS', 'Group of Seven (G-7)'),
('GSP', 'Salafist Group'),
('GSS', 'Group of Seventy-Seven (G-77)'),
('HCH', 'UN High Commission for Human Rights'),
('HCR', 'UN High Commission for Refugees'),
('HEZ', 'Hezbullah'),
('HIP', 'Highly Indebted Poor Countries (HIPC)'),
('HMS', 'Hamas'),
('HRW', 'Human Rights Watch'),
('IAC', 'Inter-African Coffee Organization (IACO)'),
('IAD', 'Intergovernmental Authority on Development (IGAD)'),
('IAE', 'International Atomic Energy Agency (IAEA)'),
('IAF', 'Islamic Action Front'),
('ICC', 'International Criminal Court'),
('ICG', 'International Crisis Group'),
('ICJ', 'International Court of Justice (ICJ)'),
('ICO', 'International Cocoa Organization (ICCO)'),
('IDB', 'Islamic Development Bank'),
('IGC', 'International Grains Council'),
('IHF', 'International Helsinki Federation for Human Rights'),
('ILO', 'International Labor Organization'),
('IMF', 'International Monetary Fund (IMF)'),
('IOM', 'International Organization for Migration'),
('IPU', 'Inter-Parliamentary Union'),
('IRC', 'Red Cross'),
('ISJ', 'Palestinian Islamic Jihad'),
('ITP', 'Interpol'),
('JUR', 'International Commission of Jurists'),
('KDP', 'Kurdish Democratic Party (KDP)'),
('KID', 'United Nations Children?s Fund (UNICEF)'),
('LBA', 'Israeli Labor Party'),
('LKD', 'Likud Party'),
('MBR', 'Muslim Brotherhood'),
('MRZ', 'Meretz Party'),
('MSF', 'Medecins Sans Frontieres (Doctors Without Borders)'),
('MSP', 'Movement of the Society for Peace'),
('NAT', 'North Atlantic Treaty Organization (NATO)'),
('NEP', 'New Economic Partnership for Africa?s Development'),
('NON', 'Organization of Non-Aligned Countries'),
('OAS', 'Organization of American States'),
('OAU', 'Organization of African Unity (OAU)'),
('OIC', 'Organization of Islamic Conferences (OIC)'),
('OPC', 'Organization of Petroleum Exporting Countries (OPEC)'),
('PAP', 'Pan-African Parliament'),
('PFL', 'People''s Front for the Liberation of Palestine (PFLP)'),
('PLF', 'Palestine Liberation Front'),
('PLO', 'Palestine Liberation Organization'),
('PLS', 'Polisario Guerillas'),
('PMD', 'People''s Mujahedeen'),
('PRC', 'Paris Club'),
('PSE', 'Occupied Palestinian Territories'),
('RCR', 'Red Crescent'),
('RND', 'Democratic National Rally'),
('SAA', 'South Asian Association'),
('SAD', 'Southern African Development Community'),
('SCE', 'Council of Security and Cooperation in Europe (OSCE)'),
('SHA', 'Shas Party'),
('SOT', 'Southeast Asia Collective Defense Treaty (SEATO)'),
('TAL', 'Taliban'),
('UEM', 'Economic and Monetary Union of West Africa (UEMOA)'),
('UNO', 'United Nations'),
('WAD', 'West Africa Development Bank'),
('WAM', 'West Africa Monetary and Economic Union'),
('WAS', 'Economic Community of West African States (ECOWAS)'),
('WBK', 'World Bank'),
('WCT', 'International War Crimes Tribunals'),
('WEF', 'World Economic Forum'),
('WFP', 'World Food Program'),
('WHO', 'World Health Organization'),
('WTO', 'World Trade Organization'),
('WTO', 'World Trade Organization (WTO)'),
('XFM', 'Oxfam');
YFLUSH gdelt.groups;

CREATE TABLE gdelt.countries (code VARCHAR(max), country VARCHAR(max)) DISTRIBUTE REPLICATE;
GRANT ALL ON TABLE gdelt.countries TO public;
INSERT INTO gdelt.countries VALUES
('WSB', 'West Bank'),
('BAG', 'Baghdad'),
('GZS', 'Gaza Strip'),
('AFR', 'Africa'),
('ASA', 'Asia'),
('BLK', 'Balkans'),
('CRB', 'Caribbean'),
('CAU', 'Caucasus'),
('CFR', 'Central Africa'),
('CAS', 'Central Asia'),
('CEU', 'Central Europe'),
('EIN', 'East Indies'),
('EAF', 'Eastern Africa'),
('EEU', 'Eastern Europe'),
('EUR', 'Europe'),
('LAM', 'Latin America'),
('MEA', 'Middle East'),
('MDT', 'Mediterranean'),
('NAF', 'North Africa'),
('NMR', 'North America'),
('PGS', 'Persian Gulf'),
('SCN', 'Scandinavia'),
('SAM', 'South America'),
('SAS', 'South Asia'),
('SEA', 'Southeast Asia'),
('SAF', 'Southern Africa'),
('WAF', 'West Africa'),
('WST', 'The West'),
('AFG', 'Afghanistan'),
('ALA', 'Aland Islands'),
('ALB', 'Albania'),
('DZA', 'Algeria'),
('ASM', 'American Samoa'),
('AND', 'Andorra'),
('AGO', 'Angola'),
('AIA', 'Anguilla'),
('ATG', 'Antigua and Barbuda'),
('ARG', 'Argentina'),
('ARM', 'Armenia'),
('ABW', 'Aruba'),
('AUS', 'Australia'),
('AUT', 'Austria'),
('AZE', 'Azerbaijan'),
('BHS', 'Bahamas'),
('BHR', 'Bahrain'),
('BGD', 'Bangladesh'),
('BRB', 'Barbados'),
('BLR', 'Belarus'),
('BEL', 'Belgium'),
('BLZ', 'Belize'),
('BEN', 'Benin'),
('BMU', 'Bermuda'),
('BTN', 'Bhutan'),
('BOL', 'Bolivia'),
('BIH', 'Bosnia and Herzegovina'),
('BWA', 'Botswana'),
('BRA', 'Brazil'),
('VGB', 'British Virgin Islands'),
('BRN', 'Brunei Darussalam'),
('BGR', 'Bulgaria'),
('BFA', 'Burkina Faso'),
('BDI', 'Burundi'),
('KHM', 'Cambodia'),
('CMR', 'Cameroon'),
('CAN', 'Canada'),
('CPV', 'Cape Verde'),
('CYM', 'Cayman Islands'),
('CAF', 'Central African Republic'),
('TCD', 'Chad'),
('CHL', 'Chile'),
('CHN', 'China'),
('COL', 'Columbia'),
('COM', 'Comoros'),
('COD', 'Democratic Republic of the Congo'),
('COG', 'People''s Republic of the Congo'),
('COK', 'Cook Islands'),
('CRI', 'Costa Rica'),
('CIV', 'Ivory Coast'),
('HRV', 'Croatia'),
('CUB', 'Cuba'),
('CYP', 'Cyprus'),
('CZE', 'Czech Republic'),
('DNK', 'Denmark'),
('DJI', 'Djibouti'),
('DMA', 'Dominica'),
('DOM', 'Dominican Republic'),
('TMP', 'East Timor'),
('ECU', 'Ecuador'),
('EGY', 'Egypt'),
('SLV', 'El Salvador'),
('GNQ', 'Equatorial Guinea'),
('ERI', 'Eritrea'),
('EST', 'Estonia'),
('ETH', 'Ethiopia'),
('FRO', 'Faeroe Islands'),
('FLK', 'Falkland Islands'),
('FJI', 'Fiji'),
('FIN', 'Finland'),
('FRA', 'France'),
('GUF', 'French Guiana'),
('PYF', 'French Polynesia'),
('GAB', 'Gabon'),
('GMB', 'Gambia'),
('GEO', 'Georgia'),
('DEU', 'Germany'),
('GHA', 'Ghana'),
('GIB', 'Gibraltar'),
('GRC', 'Greece'),
('GRL', 'Greenland'),
('GRD', 'Grenada'),
('GLP', 'Guadeloupe'),
('GUM', 'Guam'),
('GTM', 'Guatemala'),
('GIN', 'Guinea'),
('GNB', 'Guinea-Bissau'),
('GUY', 'Guyana'),
('HTI', 'Haiti'),
('VAT', 'Vatican City'),
('HND', 'Honduras'),
('HKG', 'Hong Kong'),
('HUN', 'Hungary'),
('ISL', 'Iceland'),
('IND', 'India'),
('IDN', 'Indonesia'),
('IRN', 'Iran'),
('IRQ', 'Iraq'),
('IRL', 'Ireland'),
('IMY', 'Isle of Man'),
('ISR', 'Israel'),
('ITA', 'Italy'),
('JAM', 'Jamaica'),
('JPN', 'Japan'),
('JOR', 'Jordan'),
('KAZ', 'Kazakhstan'),
('KEN', 'Kenya'),
('KIR', 'Kiribati'),
('PRK', 'North Korea'),
('KOR', 'South Korea'),
('KWT', 'Kuwait'),
('KGZ', 'Kyrgyzstan'),
('LAO', 'Laos'),
('LVA', 'Latvia'),
('LBN', 'Lebanon'),
('LSO', 'Lesotho'),
('LBR', 'Liberia'),
('LBY', 'Libya'),
('LIE', 'Liechtenstein'),
('LTU', 'Lithuania'),
('LUX', 'Luxembourg'),
('MAC', 'Macao'),
('MKD', 'Macedonia'),
('MDG', 'Madagascar'),
('MWI', 'Malawi'),
('MYS', 'Malaysia'),
('MDV', 'Maldives'),
('MLI', 'Mali'),
('MLT', 'Malta'),
('MHL', 'Marshall Islands'),
('MTQ', 'Martinique'),
('MRT', 'Mauritania'),
('MUS', 'Mauritius'),
('MYT', 'Mayotte'),
('MEX', 'Mexico'),
('FSM', 'Micronesia'),
('MDA', 'Moldova'),
('MCO', 'Monaco'),
('MNG', 'Mongolia'),
('MTN', 'Montenegro'),
('MSR', 'Montserrat'),
('MAR', 'Morocco'),
('MOZ', 'Mozambique'),
('MMR', 'Myanmar'),
('NAM', 'Namibia'),
('NRU', 'Nauru'),
('NPL', 'Nepal'),
('NLD', 'Netherlands'),
('ANT', 'Netherlands Antilles'),
('NCL', 'New Caledonia'),
('NZL', 'New Zealand'),
('NIC', 'Nicaragua'),
('NER', 'Niger'),
('NGA', 'Nigeria'),
('NIU', 'Niue'),
('NFK', 'Norfolk Island'),
('MNP', 'Northern Mariana Islands'),
('NOR', 'Norway'),
('PSE', 'Occupied Palestinian Territory'),
('OMN', 'Oman'),
('PAK', 'Pakistan'),
('PLW', 'Palau'),
('PAN', 'Panama'),
('PNG', 'Papua New Guinea'),
('PRY', 'Paraguay'),
('PER', 'Peru'),
('PHL', 'Philippines'),
('PCN', 'Pitcairn'),
('POL', 'Poland'),
('PRT', 'Portugal'),
('PRI', 'Puerto Rico'),
('QAT', 'Qatar'),
('REU', 'Runion'),
('ROM', 'Romania'),
('RUS', 'Russia'),
('RWA', 'Rwanda'),
('SHN', 'Saint Helena'),
('KNA', 'Saint Kitts-Nevis'),
('LCA', 'Saint Lucia'),
('SPM', 'Saint Pierre and Miquelon'),
('VCT', 'Saint Vincent and the Grenadines'),
('WSM', 'Samoa'),
('SMR', 'San Marino'),
('STP', 'Sao Tome and Principe'),
('SAU', 'Saudi Arabia'),
('SEN', 'Senegal'),
('SRB', 'Serbia'),
('SYC', 'Seychelles'),
('SLE', 'Sierra Leone'),
('SGP', 'Singapore'),
('SVK', 'Slovakia'),
('SVN', 'Slovenia'),
('SLB', 'Solomon Islands'),
('SOM', 'Somalia'),
('ZAF', 'South Africa'),
('ESP', 'Spain'),
('LKA', 'Sri Lanka'),
('SDN', 'Sudan'),
('SUR', 'Suriname'),
('SJM', 'Svalbard and Jan Mayen Islands'),
('SWZ', 'Swaziland'),
('SWE', 'Sweden'),
('CHE', 'Switzerland'),
('SYR', 'Syria'),
('TWN', 'Taiwan'),
('TJK', 'Tajikistan'),
('TZA', 'Tanzania'),
('THA', 'Thailand'),
('TGO', 'Togo'),
('TKL', 'Tokelau'),
('TON', 'Tonga'),
('TTO', 'Trinidad and Tobago'),
('TUN', 'Tunisia'),
('TUR', 'Turkey'),
('TKM', 'Turkmenistan'),
('TCA', 'Turks and Caicos Islands'),
('TUV', 'Tuvalu'),
('UGA', 'Uganda'),
('UKR', 'Ukraine'),
('ARE', 'United Arab Emirates'),
('GBR', 'United Kingdom'),
('USA', 'United States'),
('VIR', 'United States Virgin Islands'),
('URY', 'Uruguay'),
('UZB', 'Uzbekistan'),
('VUT', 'Vanuatu'),
('VEN', 'Venezuela'),
('VNM', 'Vietnam'),
('WLF', 'Wallis and Futuna Islands'),
('ESH', 'Western Sahara'),
('YEM', 'Yemen'),
('ZMB', 'Zambia'),
('ZWE', 'Zimbabwe');
YFLUSH gdelt.countries;

-- Setup EXTERNAL objects
CREATE EXTERNAL STORAGE gdelt_storage
  TYPE s3
  ENDPOINT 'https://s3.us-east-1.amazonaws.com/'
  REGION 'us-east-1';
GRANT ALL ON EXTERNAL STORAGE gdelt_storage TO public;

CREATE EXTERNAL FORMAT gdelt_format
  TYPE text
  WITH (
      delimiter '\t'
    , num_header_lines 0
    , on_invalid_char 'REPLACE'
    , on_unescaped_embedded_quote 'PRESERVE'
    , on_missing_field 'SUPPLYNULL'
    , on_extra_field 'REMOVE'
    , on_string_too_long 'TRUNCATE'
  );
GRANT ALL ON EXTERNAL FORMAT gdelt_format TO public;

CREATE EXTERNAL LOCATION gdelt_location
  PATH 'gdelt-open-data'
  EXTERNAL STORAGE gdelt_storage
  EXTERNAL FORMAT gdelt_format;
GRANT ALL ON EXTERNAL LOCATION gdelt_location TO public;
